### ISSUE TITLE
[PE-D][Tester A] Incorrect feature description

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T14-3/tp#103]
Incorrect feature description for the finding of expenditure records.

![Screenshot 2023-03-31 at 5.35.47 PM.png](https://raw.githubusercontent.com/MustafaAH10/ped/main/files/2d054af8-9416-4b92-a279-814b8e8453a9.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: MustafaAH10/ped#8

**Comment by TzeLoong** [comment]
Addressed
