### ISSUE TITLE
[PE-D][Tester D] Viewtype DATE does not work

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2113-T14-3/tp#105]
Expected: The feature should work as expected.
Actual: The feature does not work and an error whereby invalid expenditure is thrown.

![Screenshot 2023-03-31 at 5.42.02 PM.png](https://raw.githubusercontent.com/woowenjun99/ped/main/files/38a228fd-3399-4270-be60-b07a0493b764.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: woowenjun99/ped#11

**Comment by dsicol** [comment]
"viewtype" takes in an expenditure input and displays an expenditure list falling under the expenditure type
