### ISSUE TITLE
Code Review: Darren

### ISSUE THREAD

**Issue by cheehengk** [AY2223S2-CS2113-T14-3/tp#113]
Hi Darren, here are some comments you can consider to improve your functional code quality :)

1. In ExpenditureList, sortAmount and sortDate methods seem to have some repeated code. You can consider having them use a common, separate method if they are executing the same set of operations.

2. In TxtFileStatus, line 66 to 144 is a very long method. Consider having each case statement call a particular method instead of having all the operations within the case block.

**Comment by dsicol** [comment]
Have refactored the code to comply better with code quality
