### ISSUE TITLE
Code Review: Tze Loong

### ISSUE THREAD

**Issue by cheehengk** [AY2223S2-CS2113-T14-3/tp#115]
Hi Tze Loong, here are some comments you can consider to improve your functional code quality :)

1. In EditCommand, the 'execute' method is very long and having too many things done in a single method. You can consider breaking the method down into smaller ones. The name 'execute' is also rather vague.

2. In the same class, EditCommand, try to have some blank lines to increase the readability in the if-else blocks, especially since you are using rather long class and method names.

**Comment by TzeLoong** [comment]
Thank you for your feedback! I have refactored the code to comply better with code quality
