### ISSUE TITLE
DG Review: UML diagram complexity

### ISSUE THREAD

**Issue by cheehengk** [AY2223S2-CS2113-T14-3/tp#74]
Some class or sequence diagrams (see screenshots below) are are overly extensive, which affects readability and does not help with or complement the text in the explanation. Consider showing the key aspects of the diagrams only, instead of the entire class/operation.

Also, it is noted that there seem to only be 2 class diagrams and many sequence diagrams, and not object diagram. Remember that each command is not limited to the use of sequence diagrams only, and you may want to use other UML diagrams if it can better help you explain.

![Screenshot 2023-03-31 at 1 32 58 AM](https://user-images.githubusercontent.com/88090694/228918279-80b81376-4e2c-4787-a85c-b19db4fa4a59.png)
![Screenshot 2023-03-31 at 1 33 06 AM](https://user-images.githubusercontent.com/88090694/228918306-006716f1-8309-4c4d-9c15-7d88b98b640f.png)

**Comment by itszhixuan** [comment]
@dsicol You may close this issue once the UML diagram for command package is simplified. UML diagram for parser has been simplified.

**Comment by dsicol** [comment]
The command package diagram has been simplfied
