### ISSUE TITLE
DG Review: Formatting and other issues

### ISSUE THREAD

**Issue by cheehengk** [AY2223S2-CS2113-T14-3/tp#77]
The instructions for manual testing is rather lengthy with many instructions, that is good. However, work on the formatting so it is easier for testers to read. For instance, commands meant to be typed directly onto CLI can be styled in grey highlight. 

Under section 3.4 Command Component, a table might be better suited to show the responsibilities of each command class.

Other more minor issues with regards to formatting and typos has been covered during tutorial. Do remember to also finish up on the missing sections, non-functional requirements, and glossary if any. Glossary can help to explain what you meant by API in section 3.3 as well.

![Screenshot 2023-03-31 at 2 10 17 AM](https://user-images.githubusercontent.com/88090694/228927291-c7eb3a89-2be0-491c-9786-1bb44d28403d.png)

**Comment by itszhixuan** [comment]
All suggestions here are addressed, will close this now
