### ISSUE TITLE
[PE-D][Tester D] Expenditure Command Bug 2

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-T14-3/tp#87]
Expected: Keying the valid date twice leads to date time error
Actual: I should receive an error that I am unable to key in the date more than once

![Screenshot 2023-03-31 at 5.04.48 PM.png](https://raw.githubusercontent.com/woowenjun99/ped/main/files/de69a73d-cfe5-49eb-acc2-ec50780bbf51.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: woowenjun99/ped#4

**Comment by dsicol** [comment]
Fix bugs. Will add to developer and user guides that descriptions will not be restricted and users will have the freedom to input any non-empty description
